name: camera_bloc
description:  Camera Interface.
version: 0.0.1
homepage: https://github.com/SobolevWladimir/camera_bloc

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  camera: ^0.10.0+1
  permission_handler: ^10.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
